version: "3"

services:
  web-server:
    image: nexo-hello-world
    ports:
      - 80:80

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    secrets:
      - mysql_password
      - mysql_root_password
    environment:
      MYSQL_DATABASE: nexo-db
      MYSQL_USER: nexo
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

volumes:
  mysql: